<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.1.386
*/

require_once('form_process.php');

$form = array(
	'subject' => '자유게시판 Form 제출',
	'heading' => '새 양식 제출',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => '선택한 상태',
		'checkbox_unchecked' => '선택하지 않은 상태',
		'submitted_from' => '웹 사이트에서 제출된 양식: %s',
		'submitted_by' => '방문자 IP 주소: %s',
		'too_many_submissions' => '최근 이 IP에서 너무 많은 메시지가 전송됨',
		'failed_to_send_email' => '이메일 전송 실패',
		'invalid_reCAPTCHA_private_key' => '잘못된 reCAPTCHA 개인 키',
		'invalid_reCAPTCHA2_private_key' => '잘못된 reCAPTCHA 2.0 개인 키.',
		'invalid_reCAPTCHA2_server_response' => '잘못된 reCAPTCHA 2.0 서버 응답.',
		'invalid_field_type' => '알 수 없는 필드 유형\'%s\'.',
		'invalid_form_config' => '\'%s\' 필드에 잘못된 구성이 있습니다.',
		'unknown_method' => '알 수 없는 서버 요청 방법'
	),
	'email' => array(
		'from' => 'imago018@naver.com',
		'to' => 'imago018@naver.com'
	),
	'fields' => array(
		'custom_U60565' => array(
			'order' => 1,
			'type' => 'string',
			'label' => '이름',
			'required' => true,
			'errors' => array(
				'required' => '\'이름\' 필드가 필요합니다.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => '이메일',
			'required' => true,
			'errors' => array(
				'required' => '\'이메일\' 필드가 필요합니다.',
				'format' => '\'이메일\' 필드에 잘못된 이메일이 있습니다.'
			)
		),
		'custom_U60570' => array(
			'order' => 3,
			'type' => 'string',
			'label' => '메시지',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U61898' => array(
			'order' => 4,
			'type' => 'string',
			'label' => '집 주소',
			'required' => true,
			'errors' => array(
				'required' => '\'집 주소\' 필드가 필요합니다.'
			)
		),
		'custom_U61910' => array(
			'order' => 5,
			'type' => 'string',
			'label' => '시/도',
			'required' => true,
			'errors' => array(
				'required' => '\'시/도\' 필드가 필요합니다.'
			)
		),
		'custom_U61922' => array(
			'order' => 6,
			'type' => 'string',
			'label' => '구/동',
			'required' => true,
			'errors' => array(
				'required' => '\'구/동\' 필드가 필요합니다.'
			)
		),
		'custom_U61934' => array(
			'order' => 7,
			'type' => 'string',
			'label' => '우편 번호',
			'required' => true,
			'errors' => array(
				'required' => '\'우편 번호\' 필드가 필요합니다.'
			)
		),
		'custom_U61946' => array(
			'order' => 8,
			'type' => 'string',
			'label' => '국가',
			'required' => true,
			'errors' => array(
				'required' => '\'국가\' 필드가 필요합니다.'
			)
		)
	)
);

process_form($form);
?>
